export const dataSkills = [
  {
    id: 1,
    iconClass: 'devicon-html5-plain-wordmark colored',
    cardClass: 'htmlCard',
    style: 'shadow-orange-500',
    title: 'HTML',
  },
  {
    id: 2,
    cardClass: 'cssCard',
    iconClass: 'devicon-css3-plain-wordmark colored',
    style: 'shadow-blue-500',
    title: 'CSS',
  },
  {
    id: 3,
    cardClass: 'sassCard',
    iconClass: 'devicon-sass-original colored',
    style: 'shadow-pink-400',
    title: 'SASS',
  },
  {
    id: 4,
    cardClass: 'javascriptCard',
    iconClass: 'devicon-javascript-plain colored',
    title: 'Javascript',
  },
  {
    id: 5,
    cardClass: 'reactCard',
    iconClass: 'devicon-react-original-wordmark colored',
    style: 'shadow-blue-600',
    title: 'React/React-Native (Expo)',
  },
  {
    id: 6,
    cardClass: 'nodeCard',
    iconClass: 'devicon-nodejs-plain-wordmark colored',
    style: 'shadow-pink-400',
    title: 'NodeJs',
  },
  {
    id: 7,
    cardClass: 'expressCard',
    iconClass: 'devicon-express-original-wordmark ',
    style: 'shadow-pink-400',
    title: 'Express',
  },
  {
    id: 8,
    cardClass: 'mongoCard',
    iconClass: 'devicon-mongodb-plain-wordmark colored',
    style: 'shadow-pink-400',
    title: 'MongoDB',
  },
  {
    id: 9,
    cardClass: 'firebaseCard',
    iconClass: 'devicon-firebase-plain-wordmark colored',
    style: 'shadow-pink-400',
    title: 'Firebase',
  },
  {
    id: 10,
    title: 'GitHub',
    cardClass: 'gitCard',
    iconClass: 'devicon-git-plain-wordmark colored',
    style: 'shadow-gray-400',
  },
];
